TestDare/Controllers/VideoSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Services;
using Google.Apis.Upload;
using Google.Apis.Util.Store;
using Google.Apis.YouTube.v3;
using Google.Apis.YouTube.v3.Data;
using Umbraco.Web.Mvc;
using TestDare.Model;

namespace TestDare.Controllers
{
    public class VideoSurfaceController : SurfaceController
    {
        UserCredential credential;


        // GET: VideoSurface
        public IHtmlString RederListView()
        {
            // This method authorizes the YouTube registered User
            Authrize().Wait();
 
            //Calling AddVideos method to add Videos in Umbraco
            //GerList method is for fetching the playlist of the user from YouTube

            AddVideos(GetList());
            return Umbraco.RenderMacro("DisplayVideoList");
        }


        private async Task Authrize()
        {
            string filePath = Server.MapPath(Url.Content("~/Json/youtube.json"));

            using (var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read))
            {
                credential = await GoogleWebAuthorizationBroker.AuthorizeAsync(
                    GoogleClientSecrets.Load(stream).Secrets,
                    // This OAuth 2.0 access scope allows for read-only access to the authenticated 
                    // user's account, but not other types of account access.
                    new[] { YouTubeService.Scope.YoutubeReadonly },
                    "user",
                    CancellationToken.None,
                    new FileDataStore(this.GetType().ToString())
                );
            }
        }


        private List<PlayListItem> GetList()
        {

            
            // declaring the variable to save the list of videos fetched from YouTube Playlist
            List<PlayListItem> playList = new List<PlayListItem>();
            var youtubeService = new YouTubeService(new BaseClientService.Initializer()
            {
                HttpClientInitializer = credential,
                ApplicationName = "Google.Apis.YouTube.Samples.PlaylistUpdates",
            });

            var channelsListRequest = youtubeService.Channels.List("contentDetails");
            channelsListRequest.Mine = true;

            // Retrieve the contentDetails part of the channel resource for the authenticated user's channel.
            var channelsListResponse =  channelsListRequest.Execute();

            foreach (var channel in channelsListResponse.Items)
            {
                // From the API response, extract the playlist ID that identifies the list
                // of videos uploaded to the authenticated user's channel.
                var uploadsListId = channel.ContentDetails.RelatedPlaylists.Uploads;

                Console.WriteLine("Videos in list {0}", uploadsListId);

                var nextPageToken = "";
                while (nextPageToken != null)
                {
                    var playlistItemsListRequest = youtubeService.PlaylistItems.List("snippet");
                    
                    playlistItemsListRequest.PlaylistId = "PL1J8WVAVtJJ3KKoISBeiFZvaFrNW0WL6G";
                    playlistItemsListRequest.MaxResults = 50;
                    playlistItemsListRequest.PageToken = nextPageToken;

                    // Retrieve the list of videos uploaded to the authenticated user's channel.
                    var playlistItemsListResponse =  playlistItemsListRequest.Execute();
                    var videoBaseUrl = "https://www.youtube.com/watch?v=";

                    foreach (var playlistItem in playlistItemsListResponse.Items)
                    {
                        playList.Add(new PlayListItem { Title = playlistItem.Snippet.Title,
                            ThumpnailImage = playlistItem.Snippet.Thumbnails.Default__.Url,
                            VideoUrl = videoBaseUrl+playlistItem.Snippet.ResourceId.VideoId,
                            VideoId= playlistItem.Snippet.ResourceId.VideoId
                        });
                        // Print information about each video.
                        Console.WriteLine("{0} ({1})", playlistItem.Snippet.Title, playlistItem.Snippet.Description);
                    }

                    nextPageToken = playlistItemsListResponse.NextPageToken;
                }
            }

            return playList;
        }


        public void AddVideos(List<PlayListItem> items)
        {
            var contentService = Services.ContentService;
            var content = Umbraco.Content(1147);
            var listVideos = content.Children.ToList();


            var ids = listVideos.Select(e => 
             e.GetProperty("videoId").GetValue()
            ).ToList();

            var filterResults = items.Where(m => ! ids.Contains(m.VideoId)).ToList();


            foreach (var item in filterResults)
            {
                
                var videoContent = contentService.CreateAndSave("YouTubeVideo", 1147, "videoItem");
                videoContent.SetValue("VideoDescription", item.Title);
                videoContent.SetValue("VideoThumbnail", item.ThumpnailImage);
                videoContent.SetValue("VideoUrl", item.VideoUrl);
                videoContent.SetValue("videoId", item.VideoId);
                contentService.SaveAndPublish(videoContent);
            }
        }



    }



}

TestDare/Views/Blog.cshtml
@using ContentModels = Umbraco.Web.PublishedModels;
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Blog>
@using Umbraco.Web;
@{
    Layout = "master.cshtml";
}
@Html.Partial("~/Views/Partials/SectionHeader.cshtml")

<section class="section">

    <div class="container">
        @Umbraco.RenderMacro("latestBlogposts",
            new
            {
                numberOfPosts = Model.HowManyPostsShouldBeShown,
                startNodeId = Model.Id
            })
        @{
        }
    </div>

</section>

TestDare/Views/Blogpost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Blogpost>
@using ContentModels = Umbraco.Web.PublishedModels;
    @{
    Layout = "master.cshtml";
}
@Html.Partial("~/Views/Partials/SectionHeader.cshtml")

<section class="section">
    <div class="container">
        <article>
            <div class="blogpost-meta">
                <small class="blogpost-date">@Model.CreateDate.ToShortDateString()</small>
                <span class="blogpost-cat">
                    @Html.Partial("~/Views/Partials/CategoryLinks.cshtml", Model.Categories)
                </span>
            </div>
            <h3>@Model.Excerpt</h3>
            @Html.GetGridHtml(Model, "bodyText", "bootstrap3-fluid")
            <!-- todo: implement discus comments -->
        </article>
    </div>
</section>

TestDare/Views/MacroPartials/DisplayVideoList.cshtml
@using System.Configuration
@using System.Xml


@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
    // Getting List Of Videos from Umbraco

    var videosList = Model.Content.Descendants();
}

<link rel="stylesheet" type="text/css" href="~/css/videolist.css" />



<!-- Top menu -->
<div class="w3-top">
    <div class="w3-white w3-xlarge topmenuWidth">

        <div class="w3-center w3-padding-16">Amazing Videos</div>
    </div>
</div>



<div class="w3-main w3-content w3-padding mainContainerWidth">

    <a href='/videolist' class="GFG">
        Refresh
    </a>
    <div class="w3-row-padding w3-padding-16 w3-center">

        @foreach (IPublishedContent item in videosList)
        {

            string thumbnailImageUrl = string.Empty;
            string videoUrl = string.Empty;
            string title = string.Empty;
            if (item.HasValue("VideoDescription"))
            {
                title = Convert.ToString(item.Value("VideoDescription"));

            }

            if (item.HasValue("VideoThumbnail"))
            {
                thumbnailImageUrl = Convert.ToString(item.Value("VideoThumbnail"));
            }

            if (item.HasValue("VideoUrl"))
            {
                videoUrl = Convert.ToString(item.Value("VideoUrl"));
            }




            <div class="w3-quarter">
                <img src="@thumbnailImageUrl" alt="Sandwich" class="componentWidth">
                <a href="@videoUrl"><h3 class="truncate">@title</h3></a>

            </div>

            }

    </div>

</div>

TestDare/Views/MacroPartials/FeaturedProducts.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@*
    This snippet lists the items from a Multinode tree picker, using the pickers default settings.
    Content Values stored as xml.

    To get it working with any site's data structure, set the selection equal to the property which has the
    multinode treepicker (so: replace "PropertyWithPicker" with the alias of your property).
*@

@{ var selection = CurrentPage.PropertyWithPicker.Split(','); }

<ul>
    @foreach (var id in selection)
    {
        var item = Umbraco.Content(id);
        <li>
            <a href="@item.Url">@item.Name</a>
        </li>
    }
</ul>

TestDare/Views/MacroPartials/LatestBlogposts.cshtml
@using ContentModels = Umbraco.Web.PublishedModels;
@using Umbraco.Web;
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var startNodeId = Model.MacroParameters["startNodeId"] != null ? Model.MacroParameters["startNodeId"] : Model.Content.Id;


    var numberOfPosts = 3;
    if (Model.MacroParameters["numberOfPosts"] != null)
    {
        int.TryParse((string)Model.MacroParameters["numberOfPosts"], out numberOfPosts);
    }


}
@if (startNodeId != null)
{
    @* Get the starting page *@
    var startNode = Umbraco.Content(startNodeId);

    if (startNode == null)
    {
        <div class="blogposts">
            <h1>There are no posts at this time, try again later.</h1>
        </div>

        return;
    }

    //Gets all blogposts to calculate pages
    var blogposts = startNode.Children.OrderBy(x => x.CreateDate).ToList();
    var pageCount = (int)Math.Ceiling((double)blogposts.Count / (double)numberOfPosts);
    //gets the page from the querystring and sets it to one if it is out of range
    var page = 1;
    if (!string.IsNullOrEmpty(Request.QueryString["page"]))
    {
        int.TryParse(Request.QueryString["page"], out page);
        if (page <= 0 || page > pageCount)
        {
            page = 1;
        }
    }
    //Gets the blogposts for the current page
    var pagedBlogposts = blogposts.Skip((page - 1) * numberOfPosts).Take(numberOfPosts).ToList();

    if (pagedBlogposts.Count > 0)
    {
        <div class="blogposts">

            @foreach (ContentModels.Blogpost post in pagedBlogposts)
            {
                <a href="@post.Url" class="blogpost">
                    <div class="blogpost-meta">
                        <small class="blogpost-date">@post.CreateDate.ToShortDateString()</small>
                        <small class="blogpost-cat">
                            @Html.Partial("~/Views/Partials/CategoryLinks.cshtml", post.Categories)
                        </small>
                    </div>
                    <h3 class="blogpost-title">@post.PageTitle</h3>
                    <div class="blogpost-excerpt">@post.Excerpt</div>
                </a>
            }
        </div>
    }

    if (blogposts.Count > numberOfPosts)
    {
        <div class="pagination">
            <nav class="nav-bar nav-bar--center">
                @if (page <= 1)
                {
                    <span class="nav-link nav-link--black nav-link--disabled">Prev</span>
                }
                else
                {
                    <a class="nav-link nav-link--black" href="@(Model.Content.Url + "?page=" + (page - 1))">Prev</a>
                }

                @for (int i = 1; i <= pageCount; i++)
                {
                    <a class="nav-link nav-link--black @(page == i ? " nav-link--active" : null)" href="@(Model.Content.Url + "?page=" + i)">@i</a>
                }
                @if (page == pageCount)
                {
                    <span class="nav-link nav-link--black nav-link--disabled">Next</span>
                }
                else
                {
                    <a class="nav-link nav-link--black" href="@(Model.Content.Url + "?page=" + (page + 1))">Next</a>
                }

            </nav>
        </div>
    }
}

TestDare/Views/Partials/CategoryLinks.cshtml
@model IEnumerable<string>
@foreach (var category in Model)
{
    <!-- TODO: Add links to categories-->
    @category
    <text> </text>
}

TestDare/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

TestDare/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;

    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }
        }else {
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Html.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Html.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

TestDare/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

TestDare/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@{
    string embedValue = Convert.ToString(Model.value);
    embedValue = embedValue.DetectIsJson() ? Model.value.preview : Model.value;
}

<div class="video-wrapper">
	@Html.Raw(embedValue)
</div>

TestDare/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

TestDare/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

TestDare/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates
@{
    var value = TemplateUtilities.ParseInternalLinks(Model.value.ToString(), Current.UmbracoContext.UrlProvider);
    value = TemplateUtilities.ResolveUrlsFromTextString(value);
    value = TemplateUtilities.ResolveMediaFromTextString(value);
}
@Html.Raw(value)

TestDare/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Composing
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();
    markup = markup.Replace("#value#", Html.ReplaceLineBreaksForHtml(HttpUtility.HtmlEncode((string)Model.value.ToString())).ToString());

    if (Model.editor.config.style != null)
    {
        markup = markup.Replace("#style#", Model.editor.config.style.ToString());
    }

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

TestDare/Views/Partials/Navigation/SubNavigation.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using Umbraco.Web;
@{
    var siteSection = Model.AncestorOrSelf(2);
    var selection = siteSection.Children.Where(x => x.IsVisible());
}

@foreach (var item in selection)
{
    <a class="nav-link nav-link--black nav-link--air-bottom @(item.IsAncestorOrSelf(Model) ? "nav-link--active" : null)" href="@item.Url">@item.Name</a>
}

TestDare/Views/Partials/Navigation/TopNavigation.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using Umbraco.Web;
@{
    var site = Model.Root();
    var selection = site.Children.Where(x => x.IsVisible());
}
<!-- comment out the following line if you want to remove the root node name from the top navigation -->
<a class="nav-link @Html.Raw(Model.Id == site.Id ? "navi-link--active" : "")" href="@site.Url">@site.Name</a>
@foreach (var item in selection)
{
    if (item.Url == "/products/")
    {
        <a class="nav-link @(item.IsAncestorOrSelf(Model) ? "nav-link--active" : null)" href="/videolist/">List Of Youtube Videos</a>
    }

    else
    {
        <a class="nav-link @(item.IsAncestorOrSelf(Model) ? "nav-link--active" : null)" href="@item.Url">@item.Name</a>
    }
}

    

TestDare/Views/Partials/SectionHeader.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
<section class="section section--themed section--header section--content-center-bottom">
    <div class="section__hero-content">
        <h1 class="no-air">@Model.GetProperty("PageTitle").GetValue()</h1>
    </div>
</section>

TestDare/Views/Partials/YouTubeVideos.cshtml
@model IEnumerable<TestDare.Controllers.PlayListItem>

@{
    ViewBag.Title = "VideoList";
}


<div class="topHeader">
    <div class="title"> <h2 class="titleDecor">Video</h2> <h2 class="titleDecor titleColor">List</h2></div>
    <div class="btnDiv">
        <button class="btn-danger btnRefresh" type="submit">Refresh</button>
    </div>
</div>
<div class="mainVideoContainer">
    @foreach (var item in Model)
    {
        <div class="videoContainer">
            <div class="videoThumbnile">
                <img src="@item.ThumpnailImage" class="imgSize" />
            </div>
            <div class="videoTitle">
                <a href="@item.VideoUrl"><label>@item.Title</label></a>
            </div>


        </div>
    }

</div>

TestDare/Views/Person.cshtml
@{
	Layout = "master.cshtml";
}
<p>Nothing to see, but we could make a lesson to display a person</p>

TestDare/Views/Product.cshtml
@inherits UmbracoViewPage<Product>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "master.cshtml";
}
<!-- for the section we want to show the shop header -->
@Html.Partial("~/Views/Partials/SectionHeader.cshtml", Model.Parent)

<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="product-image-container">
                    <img class="product-image" src="@Model.Photos.Url" alt="@Model.ProductName image" />
                </div>
            </div>
            <div class="col-md-6">
                <h1>@Model.ProductName</h1>
                <div class="product-price">@Model.Parent.GetProperty("DefaultCurrency").Value() @Model.Price.ToString("F")</div>
                <div class="product-teaser">@Model.Description</div>
                <div class="product-button">
                    <button class="button button--border--solid">Buy</button>
                </div>
                <div class="product-advantages">
                    @if (Model.Features != null)
                    {
                        foreach (var feature in Model.Features)
                        {
                            <div class="product-advantage">
                                <h4>@feature.GetProperty("featureName").Value()</h4>
                                <h5>@feature.GetProperty("featureDetails").Value()</h5>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section section--sand">
    <div class="container">
        <!-- todo: Check if grid is empty via a property value converter -->
        @Html.GetGridHtml(Model, "bodyText", "bootstrap3-fluid")
    </div>
</section>

TestDare/Views/Products.cshtml
@inherits UmbracoViewPage<ContentModels.Products>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "master.cshtml";
}
@Html.Partial("~/Views/Partials/SectionHeader.cshtml")
<section class="section">

    <div class="container">

        <!-- todo: implement category selector -->
        <!--
        <nav class="nav-bar nav-bar--center nav-bar--air-bottom">
            <a class="nav-link nav-link--black nav-link--active" href="">All</a>
            <a class="nav-link nav-link--black" href="">Clothing</a>
            <a class="nav-link nav-link--black" href="">Instruments</a>
            <a class="nav-link nav-link--black" href="">Accessories</a>
            <a class="nav-link nav-link--black" href="">Other</a>
        </nav>
        -->
        <div class="product-grid">
            @if (Model.FeaturedProducts != null)
            {
                foreach (Product product in Model.FeaturedProducts)
                {
                    <a href="@product.Url" class="product-grid__item" style="background-image: url('@product.Photos.Url')">
                        <div class="product-grid__item__overlay">
                            <div class="product-grid__item__name">@product.ProductName</div>
                            <div class="product-grid__item__price">@Model.DefaultCurrency @product.Price.ToString("F")</div>
                        </div>
                    </a>
                }
            }
        </div>
    </div>

</section>

TestDare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

TestDare/Views/contentPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ContentPage>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
    Layout = "master.cshtml";
}

@Html.Partial("~/Views/Partials/SectionHeader.cshtml")

<section class="section">

    <div class="container">

        <div class="col-md-3">
            <nav class="nav-bar nav-bar--list">
                @Html.Partial("~/Views/Partials/Navigation/SubNavigation.cshtml")
            </nav>
        </div>

        <div class="col-md-9">
            <article>
                @Html.GetGridHtml(Model, "bodyText", "bootstrap3-fluid")
            </article>
        </div>
    </div>

</section>

TestDare/Views/displayVideoItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
	Layout = null;
}

@* the fun starts here *@

TestDare/Views/videoList.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
	Layout = null;
}


<div class="container">

    @{ Html.RenderAction("RederListView", "VideoSurface");}
    

</div>